// GENERATED by tools/build_art.py — 不要手改。
// 档位尺寸/偏移/色板只有这一处真源（tools/palette.py），别在 TS 侧再抄一份。
export const FACE_TIER_NAMES = ['full', 'mid', 'mini'] as const
export type FaceTierName = (typeof FACE_TIER_NAMES)[number]

/** 一档在 faces.bin 里的位置与画布尺寸（columns x rows 终端格）。 */
export type FaceSlot = { columns: number; rows: number; offset: number }

/** 三档的画布尺寸。挑选档位（hooks/faces.ts）只看这张表，不假设各表情一样大。 */
export const FACE_TIER_SLOTS: Record<FaceTierName, { columns: number; rows: number }> = {
  full: { columns: 44, rows: 26 }, mid: { columns: 26, rows: 15 }, mini: { columns: 22, rows: 6 },
}

/** 每个表情三档，按「从大到小」排。 */
export const FACES: Record<string, Record<FaceTierName, FaceSlot>> = {
  calm: { full: { columns: 44, rows: 26, offset: 0 }, mid: { columns: 26, rows: 15, offset: 2288 }, mini: { columns: 22, rows: 6, offset: 3068 }, },
  angry: { full: { columns: 44, rows: 26, offset: 3332 }, mid: { columns: 26, rows: 15, offset: 5620 }, mini: { columns: 22, rows: 6, offset: 6400 }, },
  laugh: { full: { columns: 44, rows: 26, offset: 6664 }, mid: { columns: 26, rows: 15, offset: 8952 }, mini: { columns: 22, rows: 6, offset: 9732 }, },
  sad: { full: { columns: 44, rows: 26, offset: 9996 }, mid: { columns: 26, rows: 15, offset: 12284 }, mini: { columns: 22, rows: 6, offset: 13064 }, },
}

/** faces.bin 里每个字节是一个下标；255 = 透明，其余查这张表。 */
export const FACE_PALETTE: readonly number[] = [0x1A1410, 0x6B4A1E, 0x8A7646, 0xC99E2E, 0xE8B93C, 0xFCDF69, 0xFFF3AE, 0xFFFBE0, 0xDFD2B0, 0xF8F0D8, 0xFFFFFF]
export const FACE_TRANSPARENT = 255
