// GENERATED by tools/build_laugh.py — 不要手改。
// 尺寸/帧数/色板只有这一处真源（tools/palette.py），别在 TS 侧再抄一份。
export const LAUGH = {
  columns: 44,
  rows: 26,
  frames: 103,
  fps: 10,
  bytes: 235664,
} as const

/** laugh.bin 里每个字节是一个下标；255 = 透明，其余查这张表。 */
export const LAUGH_PALETTE: readonly number[] = [0x1A1410, 0x6B4A1E, 0x8A7646, 0xC99E2E, 0xE8B93C, 0xFCDF69, 0xFFF3AE, 0xFFFBE0, 0xDFD2B0, 0xF8F0D8, 0xFFFFFF]
export const LAUGH_TRANSPARENT = 255
