#!/usr/bin/env python3
"""生成插件里的静态表情素材。

    python3 tools/build_art.py [--preview]

输入：naiwa-images/平静可爱.jpg、naiwa-images/生气凝视.jpg、
      naiwa-images/伤心失落.jpg、naiwa-videos/glimpse.mp4 第 270 帧
输出：plugin/data/faces.bin       四表情 × 三档尺寸，每像素 1 字节调色板索引，255 = 透明
      plugin/hooks/face-meta.ts   档位表（尺寸/偏移）与色板，供 register.tsx 读

**为什么分三档**：面板能拿到几行是引擎说了算 —— 80 列 inline 只有 6~18 行，
≥110 列 dock 才有 32 行，而全身像是 26 行。只做一个尺寸，必然在某些终端上被
裁成头顶一条，看着就像「没有奶蛙」。同一个裁剪框渲染三种尺寸，register.tsx
按实际 bodyRows 挑最大的放得下的那档（见 hooks/faces.ts 的 chooseLayout）。

裁剪框是人工标注的，不要「优化」成自动检测：自动暗部检测会抓到深色手部和
阴影而不是脸，试过两轮都失败。改框 = 作者决定，改完跑 --preview 肉眼确认。
"""
from __future__ import annotations

import argparse
import hashlib
import subprocess
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
from palette import PALETTE, TRANSPARENT, preview, render  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
IMAGES = ROOT / "naiwa-images"
VIDEO = ROOT / "naiwa-videos" / "glimpse.mp4"
BIN_OUT = ROOT / "plugin" / "data" / "faces.bin"
META_OUT = ROOT / "plugin" / "hooks" / "face-meta.ts"

MOODS = ("calm", "angry", "laugh", "sad")
# (名字, 列, 行)。行数就是面板至少要给这么多行才画得下；顺序即「从大到小」的优先级。
TIERS = (("full", 44, 26), ("mid", 26, 15), ("mini", 22, 6))
IDX_TRANSPARENT = 255

# 主体 bbox 内的相对裁剪框 (left, top, right, bottom)，全部瞄准头/上半身。
FACE: dict[str, tuple[float, float, float, float]] = {
    "calm": (0.16, 0.00, 0.81, 0.61),    # 平静可爱.jpg
    "angry": (0.16, 0.00, 0.52, 0.200),  # 生气凝视.jpg —— A/B 过四组，这组脸最大且不切下巴
    "laugh": (0.00, 0.00, 1.00, 0.66),   # 视频帧，主体上 66%
    # 伤心失落.jpg —— 3/4 侧身低头，一只垂眼 + 下撇的嘴在主体左上。
    # 长宽比 ~0.85 才和 44x52 画布相当，不然会被 fit() 信箱化成一条。
    "sad": (0.00, 0.00, 0.42, 0.44),
}
SRC = {
    "calm": IMAGES / "平静可爱.jpg",
    "angry": IMAGES / "生气凝视.jpg",
    "sad": IMAGES / "伤心失落.jpg",
}
LAUGH_FRAME = 270
LAUGH_DECODE = (408, 720)  # 原生尺寸，静态帧不降采样

# 0xRRGGBB → 色板下标。render() 已经把每个像素吸附到色板上，查不到就是流水线坏了。
INDEX_OF = {(r << 16) | (g << 8) | b: i for i, (r, g, b) in enumerate(PALETTE)}


def video_frame(n: int) -> np.ndarray:
    raw = subprocess.run(
        ["ffmpeg", "-v", "error", "-i", str(VIDEO),
         "-vf", f"select=eq(n\\,{n})", "-vframes", "1",
         "-f", "rawvideo", "-pix_fmt", "rgb24", "-"],
        capture_output=True, check=True,
    ).stdout
    w, h = LAUGH_DECODE
    if len(raw) < w * h * 3:
        raise SystemExit(f"ffmpeg 没吐出第 {n} 帧（拿到 {len(raw)} 字节）")
    return np.frombuffer(raw, np.uint8)[: w * h * 3].reshape(h, w, 3)


def to_indices(grid: list[list[int]]) -> bytes:
    """0xRRGGBB 网格 → 每像素 1 字节的色板下标（255 = 透明）。"""
    out = bytearray()
    for row in grid:
        for v in row:
            if v == TRANSPARENT:
                out.append(IDX_TRANSPARENT)
            else:
                out.append(INDEX_OF[v])  # 查不到直接 KeyError，别静默画错色
    return bytes(out)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--preview", action="store_true", help="多写一份 PNG 到 _design-preview/，人眼核对用")
    args = ap.parse_args()

    grids: dict[str, dict[str, list[list[int]]]] = {}
    for mood in MOODS:
        src = video_frame(LAUGH_FRAME) if mood == "laugh" else SRC[mood]
        grids[mood] = {}
        for name, cols, rows in TIERS:
            grids[mood][name] = render(src, cols, rows, box=FACE[mood])
            print(f"  {mood}/{name}: {cols}x{rows}", file=sys.stderr)

    # 二进制按 mood 主序、档位次序排布；偏移写进 face-meta.ts，TS 侧不自己算。
    blob = bytearray()
    table: list[tuple[str, str, int, int, int]] = []
    for mood in MOODS:
        for name, cols, rows in TIERS:
            data = to_indices(grids[mood][name])
            table.append((mood, name, cols, rows, len(blob)))
            blob.extend(data)

    BIN_OUT.parent.mkdir(parents=True, exist_ok=True)
    BIN_OUT.write_bytes(blob)
    digest = hashlib.sha256(bytes(blob)).hexdigest()
    print(f"wrote {BIN_OUT.relative_to(ROOT)}  {len(blob)} B "
          f"({len(MOODS)} 表情 x {len(TIERS)} 档)  sha256 {digest[:16]}", file=sys.stderr)

    pal_ts = ", ".join(f"0x{r:02X}{g:02X}{b:02X}" for r, g, b in PALETTE)
    tier_ts = " ".join(
        f"{name}: {{ columns: {cols}, rows: {rows} }},"
        for name, cols, rows in TIERS
    )
    slots = []
    for mood in MOODS:
        entries = " ".join(
            f"{name}: {{ columns: {cols}, rows: {rows}, offset: {off} }},"
            for m, name, cols, rows, off in table if m == mood
        )
        slots.append(f"  {mood}: {{ {entries} }},")
    META_OUT.write_text(
        "// GENERATED by tools/build_art.py — 不要手改。\n"
        "// 档位尺寸/偏移/色板只有这一处真源（tools/palette.py），别在 TS 侧再抄一份。\n"
        f"export const FACE_TIER_NAMES = [{', '.join(repr(n) for n, _, _ in TIERS)}] as const\n"
        "export type FaceTierName = (typeof FACE_TIER_NAMES)[number]\n"
        "\n"
        "/** 一档在 faces.bin 里的位置与画布尺寸（columns x rows 终端格）。 */\n"
        "export type FaceSlot = { columns: number; rows: number; offset: number }\n"
        "\n"
        "/** 三档的画布尺寸。挑选档位（hooks/faces.ts）只看这张表，不假设各表情一样大。 */\n"
        "export const FACE_TIER_SLOTS: Record<FaceTierName, { columns: number; rows: number }> = {\n"
        f"  {tier_ts}\n"
        "}\n"
        "\n"
        "/** 每个表情三档，按「从大到小」排。 */\n"
        "export const FACES: Record<string, Record<FaceTierName, FaceSlot>> = {\n"
        + "\n".join(slots) + "\n"
        "}\n"
        "\n"
        "/** faces.bin 里每个字节是一个下标；255 = 透明，其余查这张表。 */\n"
        f"export const FACE_PALETTE: readonly number[] = [{pal_ts}]\n"
        f"export const FACE_TRANSPARENT = {IDX_TRANSPARENT}\n",
        encoding="utf-8",
    )
    print(f"wrote {META_OUT.relative_to(ROOT)}", file=sys.stderr)

    if args.preview:
        prev = ROOT / "_design-preview"
        prev.mkdir(exist_ok=True)
        from PIL import Image, ImageDraw
        cell, pad = 6, 10
        sheet = {m: [(f"{m}/{n}", preview(grids[m][n], cell=cell)) for n, _, _ in TIERS] for m in MOODS}
        head, gap = 20, 10
        w = max(sum(t.width + gap for _, t in row) for row in sheet.values()) + gap
        h = sum(max(t.height for _, t in row) + head + gap for row in sheet.values())
        canvas = Image.new("RGB", (w, h), (16, 16, 20))
        draw = ImageDraw.Draw(canvas)
        y = gap
        for row in sheet.values():
            x = gap
            for label, tile in row:
                draw.text((x, y), label, fill=(255, 255, 255))
                canvas.paste(tile, (x, y + head))
                x += tile.width + gap
            y += max(t.height for _, t in row) + head + gap
        canvas.resize((canvas.width * 2, canvas.height * 2), Image.NEAREST).save(prev / "30-art核对.png")
        print("预览 → _design-preview/30-art核对.png", file=sys.stderr)


if __name__ == "__main__":
    main()
