#!/usr/bin/env python3
"""生成 plugin/hooks/art.ts —— 三个静态表情的像素网格。

    python3 tools/build_art.py [--preview]

输入：naiwa-images/平静可爱.jpg、naiwa-images/生气凝视.jpg、
      naiwa-videos/glimpse.mp4 第 270 帧
输出：plugin/hooks/art.ts（`Record<Mood, number[][]>`，与雨姐 mod 的 art.ts 同构）

裁剪框是人工标注的，不要「优化」成自动检测：自动暗部检测会抓到深色手部和
阴影而不是脸，试过两轮都失败。改框 = 作者决定，改完跑 --preview 肉眼确认。
"""
from __future__ import annotations

import argparse
import hashlib
import subprocess
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
from palette import TRANSPARENT, preview, render, to_ansi  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
IMAGES = ROOT / "naiwa-images"
VIDEO = ROOT / "naiwa-videos" / "glimpse.mp4"
OUT = ROOT / "plugin" / "hooks" / "art.ts"

COLS, ROWS = 44, 26

# 主体 bbox 内的相对裁剪框 (left, top, right, bottom)，全部瞄准头/上半身。
FACE: dict[str, tuple[float, float, float, float]] = {
    "calm": (0.16, 0.00, 0.81, 0.61),    # 平静可爱.jpg
    "angry": (0.16, 0.00, 0.52, 0.200),  # 生气凝视.jpg —— A/B 过四组，这组脸最大且不切下巴
    "laugh": (0.00, 0.00, 1.00, 0.66),   # 视频帧，主体上 66%
}
SRC = {"calm": IMAGES / "平静可爱.jpg", "angry": IMAGES / "生气凝视.jpg"}
LAUGH_FRAME = 270
LAUGH_DECODE = (408, 720)  # 原生尺寸，静态帧不降采样


def video_frame(n: int) -> np.ndarray:
    raw = subprocess.run(
        ["ffmpeg", "-v", "error", "-i", str(VIDEO),
         "-vf", f"select=eq(n\\,{n})", "-vframes", "1",
         "-f", "rawvideo", "-pix_fmt", "rgb24", "-"],
        capture_output=True, check=True,
    ).stdout
    w, h = LAUGH_DECODE
    if len(raw) < w * h * 3:
        raise SystemExit(f"ffmpeg 没吐出第 {n} 帧（拿到 {len(raw)} 字节）")
    return np.frombuffer(raw, np.uint8)[: w * h * 3].reshape(h, w, 3)


def fmt(v: int) -> str:
    return "0x01000000" if v == TRANSPARENT else f"0x{v:06X}"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--preview", action="store_true", help="多写一份 ANSI/PNG 到 _design-preview/，人眼核对用")
    args = ap.parse_args()

    grids: dict[str, list[list[int]]] = {}
    for mood in ("calm", "angry", "laugh"):
        src = video_frame(LAUGH_FRAME) if mood == "laugh" else SRC[mood]
        grids[mood] = render(src, COLS, ROWS, box=FACE[mood])
        print(f"  {mood}: {COLS}x{ROWS}", file=sys.stderr)

    lines = [
        "// GENERATED by tools/build_art.py — 不要手改；改裁剪框请改脚本里的 FACE 再重跑。",
        "// 每行两像素（终端半块 ▀）：偶数下标 = 上半像素，奇数下标 = 下半像素。",
        f"// {COLS} 列 x {ROWS} 行终端格 = {COLS}x{ROWS * 2} 像素。0x01000000 = 透明。",
        "",
        "export const ART: Record<string, number[][]> = {",
    ]
    for mood, g in grids.items():
        lines.append(f"  {mood}: [")
        lines.extend("    [" + ",".join(fmt(v) for v in row) + "]," for row in g)
        lines.append("  ],")
    lines.append("}")
    lines.append("")
    # 格子数由代码推导，避免两处硬编码不一致
    lines.append(f"export const ART_COLUMNS = {COLS}")
    lines.append(f"export const ART_ROWS = {ROWS}")
    lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    text = "\n".join(lines)
    OUT.write_text(text, encoding="utf-8")
    digest = hashlib.sha256(text.encode()).hexdigest()
    print(f"wrote {OUT.relative_to(ROOT)}  {len(text)} B  sha256 {digest[:16]}", file=sys.stderr)

    if args.preview:
        prev = ROOT / "_design-preview"
        prev.mkdir(exist_ok=True)
        sheet = []
        for mood, g in grids.items():
            t = preview(g, cell=8)
            sheet.append((mood, t))
        from PIL import Image, ImageDraw
        w = sum(t.width + 12 for _, t in sheet)
        h = max(t.height for _, t in sheet) + 22
        canvas = Image.new("RGB", (w, h), (16, 16, 20))
        x = 0
        for mood, t in sheet:
            ImageDraw.Draw(canvas).text((x + 4, 5), mood, fill=(255, 255, 255))
            canvas.paste(t, (x, 22))
            x += t.width + 12
        canvas.resize((canvas.width * 2, canvas.height * 2), Image.NEAREST).save(prev / "30-art核对.png")
        with open(prev / "31-art核对.ans", "w") as fp:
            for mood, g in grids.items():
                fp.write(f"\x1b[0m\x1b[1m=== {mood} ===\x1b[0m\n{to_ansi(g)}\n")
        print(f"预览 → _design-preview/30-art核对.png 31-art核对.ans", file=sys.stderr)


if __name__ == "__main__":
    main()
